version: "4.31.0"
services:
  django:
    container_name: django
    build:
      context: ./meowexe
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./meowexe:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=fjadkslfjdljgfdis
      - ALLOWED_HOSTS=localhost, 127.0.0.1
